name: Sync Supabase Schema (Re-Baseline)

on:
  workflow_dispatch:

jobs:
  pull-schema:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Pull current schema from Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          supabase link --project-ref $PROJECT_ID --password $SUPABASE_DB_PASSWORD
          supabase db pull

      - name: Commit new baseline migration
        run: |
          git config --global user.name "Schema Sync Bot"
          git config --global user.email "bot@supabase.io"
          git add supabase/migrations
          git commit -m "chore: re-baseline schema from production" || echo "No changes to commit"
          git push
